spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-52-196-140-131.ap-northeast-1.compute.amazonaws.com:3306
    username: paul
    password: Skull034456!
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: update
    # JDBC TimeZone Setting
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  devtools:
    # livereload
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
# 한글
server:
  port: 8080
  servlet:
    encoding:
      force-response: true
  error:
    whitelabel:
      enabled: true
    include-stacktrace: always
    include-exception: true
    path: /error